apiVersion: v1
kind: Pod
metadata:
   name: flask-app-pod

spec:
  containers:
   - name: flask-app-pod-ctr
     image: imsundeepdocker/flaskapp:latest
     env:
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "admin"
        - name: MYSQL_DB
          value: "mydb"

     ports:
        - containerPort: 5000
     imagePullPolicy: Always
